'use client'

import { useState, useEffect } from 'react'
import BeaconAgent from '@/components/agents/BeaconAgent'
import { useAuth } from '@/lib/auth-context'

export default function TestBeaconPage() {
  const { user, loading } = useAuth()
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  if (!mounted || loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading Beacon Agent...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto py-8">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            🚢 CrewFlow - Beacon Agent Test
          </h1>
          <p className="text-gray-600">
            Test the hybrid AI project management capabilities of Beacon
          </p>
          {user && (
            <p className="text-sm text-gray-500 mt-2">
              Logged in as: {user.email}
            </p>
          )}
        </div>

        {/* Framework Info */}
        <div className="max-w-4xl mx-auto mb-8">
          <div className="bg-white rounded-lg shadow-sm border p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-4">Beacon Agent - Project Management Specialist</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <h3 className="font-medium text-gray-900 mb-2">Hybrid Framework: LangChain + AutoGen</h3>
                <div className="space-y-3">
                  <div className="p-3 bg-blue-50 rounded-lg">
                    <h4 className="font-medium text-blue-900 text-sm">LangChain Components:</h4>
                    <ul className="text-sm text-blue-700 space-y-1 mt-1">
                      <li>• Project planning and documentation</li>
                      <li>• Task assignment and coordination</li>
                      <li>• Progress tracking and monitoring</li>
                      <li>• Status reporting and communication</li>
                    </ul>
                  </div>
                  <div className="p-3 bg-orange-50 rounded-lg">
                    <h4 className="font-medium text-orange-900 text-sm">AutoGen Components:</h4>
                    <ul className="text-sm text-orange-700 space-y-1 mt-1">
                      <li>• Complex project workflow orchestration</li>
                      <li>• Multi-team coordination and collaboration</li>
                      <li>• Resource optimization and allocation</li>
                      <li>• Automated process design</li>
                    </ul>
                  </div>
                </div>
              </div>
              <div>
                <h3 className="font-medium text-gray-900 mb-2">Intelligent Framework Routing:</h3>
                <ul className="text-sm text-gray-600 space-y-1">
                  <li>• <strong>Complex workflows:</strong> Automatically routed to AutoGen</li>
                  <li>• <strong>Planning & reporting:</strong> Handled by LangChain</li>
                  <li>• <strong>Multi-team coordination:</strong> Orchestrated by AutoGen</li>
                  <li>• <strong>Documentation:</strong> Generated by LangChain</li>
                  <li>• <strong>Process automation:</strong> Designed with AutoGen</li>
                  <li>• <strong>Status tracking:</strong> Managed by LangChain</li>
                </ul>
              </div>
            </div>
            
            <div className="mt-6 p-4 bg-indigo-50 rounded-lg">
              <h3 className="font-medium text-indigo-900 mb-2">Sample Test Queries:</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                <div>
                  <p className="font-medium text-indigo-800">Project Planning (AutoGen):</p>
                  <p className="text-indigo-700">"Create a comprehensive project plan for a new product launch"</p>
                </div>
                <div>
                  <p className="font-medium text-indigo-800">Task Assignment (LangChain):</p>
                  <p className="text-indigo-700">"Assign development tasks to team members based on skills"</p>
                </div>
                <div>
                  <p className="font-medium text-indigo-800">Progress Tracking (LangChain):</p>
                  <p className="text-indigo-700">"Track project milestones and generate status reports"</p>
                </div>
                <div>
                  <p className="font-medium text-indigo-800">Workflow Coordination (AutoGen):</p>
                  <p className="text-indigo-700">"Design automated workflows for cross-team collaboration"</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Beacon Agent Component */}
        <BeaconAgent userId={user?.id} />

        {/* Additional Info */}
        <div className="max-w-4xl mx-auto mt-8">
          <div className="bg-white rounded-lg shadow-sm border p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-4">About Beacon's Hybrid AI Approach</h2>
            <div className="prose max-w-none text-sm text-gray-600">
              <p>
                Beacon utilizes a sophisticated hybrid approach that intelligently combines LangChain and 
                AutoGen frameworks to provide comprehensive project management capabilities:
              </p>
              <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <h4 className="font-medium text-gray-900 mb-2">LangChain Usage:</h4>
                  <ul className="space-y-1">
                    <li>• Project planning and documentation</li>
                    <li>• Task assignment and delegation</li>
                    <li>• Progress monitoring and reporting</li>
                    <li>• Stakeholder communication</li>
                    <li>• Performance analysis and insights</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-medium text-gray-900 mb-2">AutoGen Usage:</h4>
                  <ul className="space-y-1">
                    <li>• Complex project workflow design</li>
                    <li>• Multi-team coordination strategies</li>
                    <li>• Resource optimization algorithms</li>
                    <li>• Automated process orchestration</li>
                    <li>• Cross-functional collaboration</li>
                  </ul>
                </div>
              </div>
              <p className="mt-4">
                This intelligent routing ensures that simple project management tasks leverage LangChain's 
                structured approach, while complex multi-team coordination and workflow automation benefit 
                from AutoGen's multi-agent orchestration capabilities.
              </p>
              <div className="mt-4 p-3 bg-gray-50 rounded-lg">
                <h4 className="font-medium text-gray-900 mb-2">AutoGen Multi-Agent Workflow:</h4>
                <p className="text-sm text-gray-600">
                  When handling complex projects, Beacon's AutoGen system deploys specialized agents:
                </p>
                <ul className="text-sm text-gray-600 mt-2 space-y-1">
                  <li>• <strong>Project Planner:</strong> Develops comprehensive project strategies</li>
                  <li>• <strong>Resource Manager:</strong> Optimizes team and resource allocation</li>
                  <li>• <strong>Progress Monitor:</strong> Tracks performance and identifies issues</li>
                  <li>• <strong>Risk Analyst:</strong> Assesses and mitigates project risks</li>
                  <li>• <strong>Coordinator:</strong> Orchestrates multi-agent collaboration</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
